/**
 * TypeScript types for synthetic visa application data
 * Generated by openvisa-synthetic-data
 */

export type SyntheticVisaType =
  | 'student_visa'
  | 'skilled_worker_visa'
  | 'senior_specialist_worker_visa'
  | 'global_talent_visa'
  | 'spouse_partner_visa'
  | 'innovator_founder_visa';

export type SyntheticScenario =
  | 'clean_approve'
  | 'minor_issues'
  | 'major_issues'
  | 'fraudulent'
  | 'edge_case';

export type DocumentCategory =
  | 'identity'
  | 'financial'
  | 'employment'
  | 'educational'
  | 'supporting';

export type DocumentProcessor = 'document_ai' | 'gemini_vision';

export interface SyntheticAddress {
  line1?: string;
  line2?: string;
  city?: string;
  postcode?: string;
  country: string;
}

export interface SyntheticApplicant {
  application_id: string;
  first_name: string;
  last_name: string;
  date_of_birth: string;
  gender: 'Male' | 'Female';
  nationality: string;
  passport_number: string;
  passport_expiry: string;
  mrz: string;
  email: string;
  phone: string;
  current_address: SyntheticAddress;
}

export interface SyntheticDocument {
  document_id: string;
  document_type: string;
  category: DocumentCategory;
  processor: DocumentProcessor;
  file_name: string;
  file_size: number;
  upload_timestamp: string;
  extracted_fields: Record<string, unknown>;
  confidence_score: number;
  validation_status: 'pending' | 'verified' | 'rejected';
  fraud_flags: string[];
}

export interface SyntheticDecisionAudit {
  generated_at: string;
  generator_version: string;
  seed: number | null;
}

// Visa-specific data types
export interface StudentVisaData {
  cas_number: string;
  institution_name: string;
  course_title: string;
  course_level: string;
  course_start_date: string;
  course_end_date: string;
  tuition_fees: number;
  tuition_paid: number;
  maintenance_funds: number;
  english_test_type: string;
  english_overall_score: number;
  english_component_scores: Record<string, number>;
  atas_required: boolean;
  atas_certificate_number?: string;
}

export interface SkilledWorkerVisaData {
  cos_number: string;
  sponsor_name: string;
  sponsor_license_number: string;
  job_title: string;
  soc_code: string;
  annual_salary: number;
  working_hours: number;
  job_start_date: string;
  is_new_entrant: boolean;
  qualifications: Array<{
    title: string;
    institution: string;
    year: number;
  }>;
}

export interface SeniorSpecialistWorkerVisaData {
  cos_number: string;
  sponsor_name: string;
  sponsor_license_number: string;
  job_title: string;
  soc_code: string;
  annual_salary: number;
  working_hours: number;
  job_start_date: string;
  overseas_employer: string;
  overseas_employment_start: string;
  overseas_employment_months: number;
  maintenance_funds: number;
  qualifications: Array<{
    title: string;
    institution: string;
    year: number;
  }>;
}

export interface GlobalTalentVisaData {
  endorsing_body: string;
  endorsement_reference: string;
  talent_category: string;
  field_of_expertise: string;
  achievements: string[];
  publications: Array<Record<string, unknown>>;
  references: Array<Record<string, unknown>>;
}

export interface FamilyVisaData {
  relationship_type: string;
  sponsor_name: string;
  sponsor_nationality: string;
  sponsor_immigration_status: string;
  relationship_start_date: string;
  cohabitation_start_date?: string;
  marriage_date?: string;
  annual_income: number;
  income_source: string;
  accommodation_type: string;
  accommodation_address: Record<string, unknown>;
}

export interface InnovatorFounderVisaData {
  endorsing_body: string;
  endorsement_reference: string;
  business_name: string;
  business_sector: string;
  business_description: string;
  investment_amount: number;
  investment_source: string;
  team_members: Array<Record<string, unknown>>;
}

export type SyntheticVisaSpecificData =
  | StudentVisaData
  | SkilledWorkerVisaData
  | SeniorSpecialistWorkerVisaData
  | GlobalTalentVisaData
  | FamilyVisaData
  | InnovatorFounderVisaData
  | Record<string, unknown>;

export interface SyntheticApplication {
  application_id: string;
  visa_type: SyntheticVisaType;
  application_date: string;
  scenario: SyntheticScenario;
  fraud_patterns: string[];
  applicant: SyntheticApplicant;
  documents: SyntheticDocument[];
  visa_specific_data: SyntheticVisaSpecificData;
  decision_audit: SyntheticDecisionAudit;
}
