-- CREATE TABLE IF NOT EXISTS application_payload (
--     submission_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
--     source_application_id TEXT NOT NULL,
--     source_reference TEXT NOT NULL,
--     source_channel TEXT NOT NULL,
--     visa_type TEXT NOT NULL,
--     country_code TEXT NOT NULL,
--     submitted_at TIMESTAMPTZ NOT NULL,
--     caseworker_id TEXT,
--     applicant JSONB NOT NULL,
--     passport_data JSONB NOT NULL,
--     biometric_verification JSONB NOT NULL,
--     answers_personalinfo JSONB NOT NULL,
--     answers_employment JSONB NOT NULL,
--     answers_fees JSONB NOT NULL,
--     answers_englishlanguage JSONB NOT NULL,
--     answers_travelhistory JSONB NOT NULL,
--     answers_criminalrecord JSONB NOT NULL,
--     answers_healthdeclaration JSONB NOT NULL,
--     documents JSONB NOT NULL,
--     eligibility_score JSONB,
--     callback_url TEXT NOT NULL
-- );

CREATE TABLE IF NOT EXISTS submission_payload (
    submission_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    source_application_id TEXT NOT NULL,
    source_reference TEXT NOT NULL,
    source_channel TEXT NOT NULL,
    visa_type TEXT NOT NULL,
    country_code TEXT NOT NULL,
    submitted_at TIMESTAMPTZ NOT NULL,
    caseworker_id TEXT,
    applicant JSONB NOT NULL,
    passport_data JSONB NOT NULL,
    biometric_verification JSONB NULL,
    answers_personalinfo JSONB NOT NULL,
    answers_employment JSONB NOT NULL,
    answers_fees JSONB NOT NULL,
    answers_englishlanguage JSONB NOT NULL,
    answers_travelhistory JSONB NOT NULL,
    answers_criminalrecord JSONB NOT NULL,
    answers_healthdeclaration JSONB NOT NULL,
    documents JSONB NOT NULL,
    eligibility_score JSONB,
    callback_url TEXT NOT NULL
);