/**
 * Mock DIS Application View — realistic MANUAL_REVIEW scenario.
 *
 * Used by the reviewer page during Phase 2 development before live DIS
 * integration (Phase 3). Every Phase 2A UI component binds to this shape.
 *
 * Scenario: Skilled Worker applicant Rani Kumari. DIS flagged for manual
 * review due to:
 * - Font inconsistency on employment letter (fraud signal)
 * - Salary borderline (£50,253 vs £41,700 general threshold — passes, but
 *   cross-doc consistency between payslips and employment letter flagged)
 * - World-Check LOW match (PEP — politically exposed person relative)
 *
 * Most rules PASS, a couple flag REVIEW_REQUIRED. No hard blocks.
 */

import type { DISApplicationView } from '@/api-contracts/dis'

export const mockDISApplicationView: DISApplicationView = {
  // === Decision callback ===
  decision: {
    outcome: 'MANUAL_REVIEW',
    confidence: 78.4,
    processing_path: 'ESCALATED',
    risk_level: 'MEDIUM',
    overall_score: 81.2,
  },

  component_scores: {
    passport:               { score: 95, status: 'VERIFIED',       confidence: 97.1, details: 'Passport valid, MRZ checksum passed, expiry 26 months' },
    financial:              { score: 82, status: 'VERIFIED',       confidence: 92.0, details: 'Bank statement shows £118,500 lowest balance (well above £1,270 threshold). Salary credits detected.' },
    employment:             { score: 74, status: 'FLAGGED',        confidence: 94.5, details: 'Annual salary £50,253 meets general threshold £41,700. Font inconsistency detected on employment letter. Cross-doc salary check pending.' },
    english_language:       { score: 90, status: 'VERIFIED',       confidence: 89.0, details: 'IELTS Academic overall 7.5 (CEFR C1). Meets B2 minimum. Test within 2 years.' },
    immigration_compliance: { score: 100, status: 'CLEAR',         confidence: 99.0, details: 'No overstay, no deportation, no refusal at border. BRP valid.' },
    criminal_record:        { score: 95, status: 'CLEAR',          confidence: 99.0, details: 'No Interpol red notice. Police certificate clear. World-Check LOW match (PEP relative) — flagged for review.' },
    health:                 { score: 90, status: 'VERIFIED',       confidence: 88.0, details: 'TB certificate valid, issued by approved clinic (Apollo TB Screening Centre, Chennai).' },
    document_quality:       { score: 87, status: 'ACCEPTABLE',     confidence: 85.0, details: 'All documents legible. Employment letter shows minor font inconsistency (signal score 0.15).' },
    fraud_risk:             { score: 85, status: 'LOW_RISK',       confidence: 91.0, details: 'Composite fraud score 0.18 (CLEAR). Employment letter font inconsistency is the highest signal (0.15).' },
  },

  audit_log: {
    pipeline_version: '1.0.0',
    models_used: {
      document_ai: 'document-ai-v2.1',
      fraud_detection: 'vision-ai-v1.3',
      rules_engine: 'drools-v1.2',
      llm_summary: 'gemini-2.0-flash',
    },
    data_classification: 'OFFICIAL-SENSITIVE',
    processing_location: 'europe-west2',
    documents: { total: 10, successful: 10, failed: 0, errors: [] },
    rules: { total_evaluated: 20, passed: 18, failed: 0, skipped: 2 },
    external_checks: { total: 6, successful: 6, failed: 0, timed_out: 0, errors: [] },
    opa_policies: { total_evaluated: 12, passed: 10, blocked: 0, flagged: 2 },
    processing_errors: [],
    warnings: ['World-Check LOW match requires officer review (OPA-S02)'],
  },

  source_channel: 'visakey',

  // === Drools Rule Results (20 rules) ===
  rule_results: [
    // Universal (5)
    { rule_id: 'RULE-U01', rule_file: 'universal/passport_rules.drl', result: 'PASS', detail: 'Passport XK9F4A7C2 valid. Expiry 2028-06-19 (26 months remaining, ≥ 6 months required). MRZ checksum passed. HMPO verification clear.', source: 'document_extractions', visa_type: 'universal', severity: 'MANDATORY', evaluated_at: '2026-04-10T10:00:01Z' },
    { rule_id: 'RULE-U02', rule_file: 'universal/biometric_rules.drl', result: 'PASS', detail: 'Face match score 0.94 (≥ 0.85 required). Liveness PASS. MRZ PASS.', source: 'submission_payload', visa_type: 'universal', severity: 'MANDATORY', evaluated_at: '2026-04-10T10:00:01Z' },
    { rule_id: 'RULE-U03', rule_file: 'universal/sanctions_rules.drl', result: 'PASS', detail: 'World-Check result: LOW risk. PEP relative match — does not meet HIGH threshold for block. Flagged for officer review (OPA-S02).', source: 'external_checks', visa_type: 'universal', severity: 'MANDATORY', evaluated_at: '2026-04-10T10:00:02Z' },
    { rule_id: 'RULE-U04', rule_file: 'universal/duplicate_rules.drl', result: 'PASS', detail: 'No duplicate applications found. Passport number, name+DOB, and email all unique in DIS database.', source: 'dis_database', visa_type: 'universal', severity: 'MANDATORY', evaluated_at: '2026-04-10T10:00:02Z' },
    { rule_id: 'RULE-U05', rule_file: 'universal/document_confidence_rules.drl', result: 'PASS', detail: 'All 7 Critical documents have extraction confidence ≥ 0.80. Lowest: Employment Letter at 0.91.', source: 'document_extractions', visa_type: 'universal', severity: 'MANDATORY', evaluated_at: '2026-04-10T10:00:03Z' },
    // Skilled Worker (15)
    { rule_id: 'RULE-W01', rule_file: 'skilled_worker/sponsorship_rules.drl', result: 'PASS', detail: 'CoS COS-2026-7247410 is valid, assigned within 3 months, not previously used.', source: 'submission_payload', reference_data: 'cos_register_mock.json', visa_type: 'skilled_worker', severity: 'MANDATORY', evaluated_at: '2026-04-10T10:00:03Z' },
    { rule_id: 'RULE-W02', rule_file: 'skilled_worker/sponsorship_rules.drl', result: 'PASS', detail: 'Sponsor licence MER-2024-7891 (Orion Tech Solutions Ltd) is A-rated, not suspended or revoked.', source: 'submission_payload', reference_data: 'sponsor_register.csv', visa_type: 'skilled_worker', severity: 'MANDATORY', evaluated_at: '2026-04-10T10:00:03Z' },
    { rule_id: 'RULE-W03', rule_file: 'skilled_worker/salary_rules.drl', result: 'PASS', detail: 'Annual salary £50,253 meets general threshold £41,700 (Option A). Hourly rate £25.10 meets minimum £17.13. Going rate for SOC 2135 (IT Business Analyst): £41,100 — salary exceeds 100%.', source: 'submission_payload', reference_data: 'soc_going_rates.json', visa_type: 'skilled_worker', severity: 'MANDATORY', evaluated_at: '2026-04-10T10:00:04Z' },
    { rule_id: 'RULE-W04', rule_file: 'skilled_worker/salary_rules.drl', result: 'PASS', detail: 'Not applicable — applicant DOB 1993-08-14, age 32. Not a new entrant (< 26 years). General threshold applied instead.', source: 'submission_payload', reference_data: 'soc_going_rates.json', visa_type: 'skilled_worker', severity: 'MANDATORY', evaluated_at: '2026-04-10T10:00:04Z' },
    { rule_id: 'RULE-W05', rule_file: 'skilled_worker/eligibility_rules.drl', result: 'PASS', detail: 'SOC code 2135 (IT Business Analyst) is in Appendix Skilled Occupations Table 1. RQF level 6.', source: 'submission_payload', reference_data: 'eligible_soc_codes.json', visa_type: 'skilled_worker', severity: 'MANDATORY', evaluated_at: '2026-04-10T10:00:04Z' },
    { rule_id: 'RULE-W06', rule_file: 'skilled_worker/salary_rules.drl', result: 'PASS', detail: 'SOC 2135 is not on the Immigration Salary List. Standard threshold applies.', source: 'submission_payload', reference_data: 'immigration_salary_list.json', visa_type: 'skilled_worker', severity: 'ADVISORY', evaluated_at: '2026-04-10T10:00:04Z' },
    { rule_id: 'RULE-W07', rule_file: 'skilled_worker/eligibility_rules.drl', result: 'PASS', detail: 'SOC 2135 requires RQF Level 6. Applicant holds BSc Computer Science (undergraduate) from University of Birmingham — RQF Level 6 confirmed (UK institution, no ENIC lookup needed).', source: 'submission_payload', reference_data: 'eligible_soc_codes.json', visa_type: 'skilled_worker', severity: 'MANDATORY', evaluated_at: '2026-04-10T10:00:05Z' },
    { rule_id: 'RULE-W08', rule_file: 'skilled_worker/eligibility_rules.drl', result: 'PASS', detail: 'IELTS Academic overall 7.5 (CEFR C1). Meets B2 minimum requirement. Test date 2024-10-12, within 2 years. UK degree also provides exemption.', source: 'document_extractions', visa_type: 'skilled_worker', severity: 'MANDATORY', evaluated_at: '2026-04-10T10:00:05Z' },
    { rule_id: 'RULE-W09', rule_file: 'skilled_worker/financial_rules.drl', result: 'PASS', detail: 'Bank statement shows lowest balance £118,500 held for 31 days (statement period 2026-01-01 to 2026-01-31). Well above £1,270 for 28 days requirement.', source: 'document_extractions', visa_type: 'skilled_worker', severity: 'MANDATORY', evaluated_at: '2026-04-10T10:00:05Z' },
    { rule_id: 'RULE-W10', rule_file: 'skilled_worker/compliance_rules.drl', result: 'PASS', detail: 'Applicant nationality IND is in tb_test_countries.json (Appendix T). TB certificate present, outcome CLEAR, not expired (expiry 2026-08-15). Clinic: Apollo TB Screening Centre, Chennai — approved clinic lookup pending.', source: 'document_extractions', reference_data: 'tb_test_countries.json', visa_type: 'skilled_worker', severity: 'MANDATORY', evaluated_at: '2026-04-10T10:00:06Z' },
    { rule_id: 'RULE-W11', rule_file: 'skilled_worker/compliance_rules.drl', result: 'PASS', detail: 'No Interpol red notice. Police certificate shows criminal_record_disclosed: false. World-Check LOW match is PEP relative (not criminal).', source: 'external_checks', visa_type: 'skilled_worker', severity: 'MANDATORY', evaluated_at: '2026-04-10T10:00:06Z' },
    { rule_id: 'RULE-W12', rule_file: 'skilled_worker/compliance_rules.drl', result: 'PASS', detail: 'No overstay history, no deportation, no refusal at border. BRP ZW1234567 valid until 2026-12-31.', source: 'external_checks', visa_type: 'skilled_worker', severity: 'MANDATORY', evaluated_at: '2026-04-10T10:00:06Z' },
    { rule_id: 'RULE-W13', rule_file: 'skilled_worker/completeness_rules.drl', result: 'PASS', detail: 'Completeness score 93/100. All required documents present: Passport (20), Employment Letter (15), Payslips (15), Bank Statement (15), IELTS (10), Degree (10). Optional: P60 (5), TB Cert (5). Missing: Police Certificate (2), Utility Bill (3) — not required.', source: 'document_extractions', visa_type: 'skilled_worker', severity: 'ADVISORY', evaluated_at: '2026-04-10T10:00:07Z' },
    { rule_id: 'RULE-W14', rule_file: 'skilled_worker/compliance_rules.drl', result: 'PASS', detail: 'No document has fraud_score ≥ 0.90 (CRITICAL threshold). Highest: Employment Letter at 0.18 (CLEAR). Font inconsistency signal (0.15) noted but below threshold.', source: 'document_extractions', visa_type: 'skilled_worker', severity: 'MANDATORY', evaluated_at: '2026-04-10T10:00:07Z' },
    { rule_id: 'RULE-W15', rule_file: 'skilled_worker/sponsorship_rules.drl', result: 'PASS', detail: 'Employment start date 2026-05-01 is within 3 months of submission date 2026-04-10.', source: 'submission_payload', reference_data: 'cos_register_mock.json', visa_type: 'skilled_worker', severity: 'MANDATORY', evaluated_at: '2026-04-10T10:00:07Z' },
  ],

  // === OPA Policy Results (12 policies) ===
  opa_results: [
    // Hard (6)
    { policy_id: 'OPA-H01', policy_name: 'Sanctions_WorldCheck_HardBlock', tier: 'HARD', result: 'PASS', reason: 'World-Check result is LOW, not HIGH. Does not meet hard block threshold.', data_source: 'REUTERS_WORLDCHECK', rego_file: 'hard/sanctions.rego', evaluated_at: '2026-04-10T10:00:08Z' },
    { policy_id: 'OPA-H02', policy_name: 'Passport_Verification', tier: 'HARD', result: 'PASS', reason: 'Passport verified. MRZ valid, document not cancelled, authenticity score 0.97 (≥ 0.50).', data_source: 'PASSPORT_VERIFY', rego_file: 'hard/passport_stolen.rego', evaluated_at: '2026-04-10T10:00:08Z' },
    { policy_id: 'OPA-H03', policy_name: 'Interpol_SLTD', tier: 'HARD', result: 'PASS', reason: 'Passport not flagged as stolen, lost, revoked, or invalid in INTERPOL SLTD database.', data_source: 'INTERPOL_SLTD', rego_file: 'hard/document_fraud.rego', evaluated_at: '2026-04-10T10:00:08Z' },
    { policy_id: 'OPA-H04', policy_name: 'Auth_Session_Validation', tier: 'HARD', result: 'PASS', reason: 'Authenticated via SERVICE_TOKEN. Channel: visakey. Auth method matches X-Source-Channel header.', data_source: 'applications.auth_context', rego_file: 'hard/auth_session.rego', evaluated_at: '2026-04-10T10:00:08Z' },
    { policy_id: 'OPA-H05', policy_name: 'Document_Fraud_Score', tier: 'HARD', result: 'PASS', reason: 'No Critical document has fraud_score ≥ 0.90. Highest: Employment Letter at 0.18.', data_source: 'document_extractions', rego_file: 'hard/document_tampering.rego', evaluated_at: '2026-04-10T10:00:09Z' },
    { policy_id: 'OPA-H06', policy_name: 'Data_Residency', tier: 'HARD', result: 'PASS', reason: 'All PII stored in europe-west2. GCS, Cloud SQL, and BigQuery locations verified.', data_source: 'infrastructure_metadata', rego_file: 'hard/data_residency.rego', evaluated_at: '2026-04-10T10:00:09Z' },
    // Soft (6)
    { policy_id: 'OPA-S01', policy_name: 'Biometric_Borderline', tier: 'SOFT', result: 'PASS', reason: 'Face match score 0.94 is above 0.85 threshold. Not borderline.', data_source: 'submission_payload', rego_file: 'soft/biometric_borderline.rego', evaluated_at: '2026-04-10T10:00:09Z' },
    { policy_id: 'OPA-S02', policy_name: 'WorldCheck_Low_Medium', tier: 'SOFT', result: 'REVIEW_REQUIRED', reason: 'World-Check returned LOW risk with PEP relative match. Category: POLITICALLY_EXPOSED_PERSON. Officer must review PEP connection and assess relevance.', data_source: 'REUTERS_WORLDCHECK', rego_file: 'soft/worldcheck_low_medium.rego', evaluated_at: '2026-04-10T10:00:09Z' },
    { policy_id: 'OPA-S03', policy_name: 'Completeness_Low', tier: 'SOFT', result: 'PASS', reason: 'Completeness score 93 is above threshold 70.', data_source: 'rule_results', rego_file: 'soft/completeness_low.rego', evaluated_at: '2026-04-10T10:00:10Z' },
    { policy_id: 'OPA-S04', policy_name: 'Rapid_Submission_Bot', tier: 'SOFT', result: 'PASS', reason: 'Submission took 47 minutes (≥ 3 minute threshold). No repeat submissions from this passport/email in 30 days.', data_source: 'ingestion_metadata', rego_file: 'soft/rapid_submission.rego', evaluated_at: '2026-04-10T10:00:10Z' },
    { policy_id: 'OPA-S05', policy_name: 'Enhanced_Scrutiny_Nationality', tier: 'SOFT', result: 'PASS', reason: 'Nationality IND is not on the enhanced scrutiny list.', data_source: 'enhanced_scrutiny_nationalities.json', rego_file: 'soft/enhanced_scrutiny.rego', evaluated_at: '2026-04-10T10:00:10Z' },
    { policy_id: 'OPA-S06', policy_name: 'Infrastructure_Alerts', tier: 'SOFT', result: 'PASS', reason: 'CMEK key rotation current. TLS certificates valid. No infrastructure alerts.', data_source: 'infrastructure_metadata', rego_file: 'soft/cmek_rotation.rego', evaluated_at: '2026-04-10T10:00:10Z' },
  ],

  // === External Check Results (6 APIs) ===
  external_checks: [
    { request_id: 'ext-001', dis_application_id: 'dis-app-001', document_id: null, check_type: 'WORLDCHECK', check_status: 'FLAGGED', risk_level: 'LOW', confidence_score: 0.72, flags: { pep_relative_match: true, categories: ['POLITICALLY_EXPOSED_PERSON'] }, responded_at: '2026-04-10T10:00:02Z', response_time_ms: 1240, details: { risk_level: 'LOW', categories_checked: ['SANCTIONS', 'PEP', 'ADVERSE_MEDIA', 'LAW_ENFORCEMENT'], lists_checked: ['OFSI', 'UN_SC', 'EU_SANCTIONS', 'US_OFAC', 'INTERPOL_RED_NOTICE'], matches_found: [{ type: 'PEP_RELATIVE', name: 'Kumar, Rajesh', relationship: 'Father-in-law', list: 'PEP_INDIA_STATE_LEVEL' }] } },
    { request_id: 'ext-002', dis_application_id: 'dis-app-001', document_id: 'doc-passport-001', check_type: 'INTERPOL_SLTD', check_status: 'CLEAR', risk_level: 'NONE', confidence_score: 0.99, flags: {}, responded_at: '2026-04-10T10:00:02Z', response_time_ms: 890, details: { is_stolen: false, is_lost: false, is_revoked: false, is_invalid: false, database_version: '2026-04-10' } },
    { request_id: 'ext-003', dis_application_id: 'dis-app-001', document_id: 'doc-passport-001', check_type: 'PASSPORT_VERIFY', check_status: 'CLEAR', risk_level: 'NONE', confidence_score: 0.98, flags: {}, responded_at: '2026-04-10T10:00:03Z', response_time_ms: 1100, details: { overall_match: true, check_digit_valid: true, authenticity: 0.97, document_status: 'VALID', has_overstay: false, has_deportation: false, has_refusal_at_border: false, current_immigration_status: 'LEAVE_TO_REMAIN' } },
    { request_id: 'ext-004', dis_application_id: 'dis-app-001', document_id: null, check_type: 'DEVICE_IP_RISK', check_status: 'CLEAR', risk_level: 'NONE', confidence_score: 0.95, flags: {}, responded_at: '2026-04-10T10:00:01Z', response_time_ms: 340, details: { ip_analysis: { is_vpn: false, is_tor: false, is_proxy: false, is_datacenter: false, is_known_fraud_ip: false }, device_analysis: { device_fingerprint_known: true, device_trust_score: 0.92 }, submission_velocity: 'NORMAL', impossible_travel: false } },
    { request_id: 'ext-005', dis_application_id: 'dis-app-001', document_id: null, check_type: 'EMAIL_PHONE_REPUTATION', check_status: 'CLEAR', risk_level: 'NONE', confidence_score: 0.93, flags: {}, responded_at: '2026-04-10T10:00:01Z', response_time_ms: 520, details: { email_analysis: { is_disposable: false, is_deliverable: true, domain_age_days: 4380, breach_count: 0, is_known_fraud_email: false }, phone_analysis: { is_valid: true, line_type: 'MOBILE', carrier: 'Vodafone UK', is_voip: false, is_virtual: false, phone_country: 'GBR', is_known_fraud_phone: false } } },
    { request_id: 'ext-006', dis_application_id: 'dis-app-001', document_id: null, check_type: 'SPONSOR_VERIFY', check_status: 'CLEAR', risk_level: 'NONE', confidence_score: 0.99, flags: {}, responded_at: '2026-04-10T10:00:03Z', response_time_ms: 210, details: { sponsor_licence_number: 'MER-2024-7891', sponsor_name: 'Orion Tech Solutions Ltd', licence_status: 'ACTIVE', licence_rating: 'A', route: 'SKILLED_WORKER', is_suspended: false, is_revoked: false } },
  ],

  // === Document Extractions (8 documents for this applicant) ===
  document_extractions: [
    { extraction_id: 'extr-001', dis_application_id: 'dis-app-001', document_id: 'doc-passport-001', document_type: 'PASSPORT', tier: 'TIER_1', criticality: 'CRITICAL', extraction_method: 'DOC_AI_ID_PARSER', processor_id: 'projects/prj-dev-dis-9666/locations/europe-west2/processors/passport-id-parser', processor_version: 'pretrained-v2.1', extraction_confidence: 0.97, raw_extraction: {}, extracted_data: { document_number: 'XK9F4A7C2', surname: 'KUMARI', given_names: 'RANI', full_name: 'RANI KUMARI', date_of_birth: '1993-08-14', nationality: 'INDIAN', sex: 'F', issue_date: '2018-06-20', expiry_date: '2028-06-19', issuing_country: 'INDIA', country_code: 'IND', document_type_code: 'P', place_of_birth: 'Delhi, India', place_of_issue: 'Ghaziabad, Uttar Pradesh, India', mrz_line_1: 'P<INDKUMARI<<RANI<<<<<<<<<<<<<<<<<<<', mrz_line_2: 'XK9F4A7C2IND9308146F2806199<<<<<<<<<<<<<', photo_hash: 'b1946ac92492d2347c6235b4d2611184', has_signature: true }, normalised_fields: { document_number: 'XK9F4A7C2', surname: 'KUMARI', given_names: 'RANI', full_name: 'KUMARI, RANI', date_of_birth: '1993-08-14', nationality_code: 'IND', sex: 'F', issue_date: '2018-06-20', expiry_date: '2028-06-19', issuing_country_code: 'IND', mrz_valid: true, mrz_checksum_passed: true, months_to_expiry: 26, is_expired: false }, fraud_score: 0.08, fraud_status: 'CLEAR', fraud_signals: { metadata_analysis: { score: 0.05, flags: [] }, font_consistency: { score: 0.02, flags: [] }, layout_anomaly: { score: 0.03, flags: [] }, document_quality: { score: 0.04, flags: [] }, cross_doc_consistency: { score: 0.10, flags: [] }, mrz_check: { score: 0.00, flags: [] }, content_plausibility: { score: 0.05, flags: [] } }, source_channel: 'visakey', gcs_raw_path: 'gs://dis-raw-uploads/dis-app-001/doc-passport-001.jpg', gcs_processed_path: 'gs://dis-processed-docs/dis-app-001/doc-passport-001.json', created_at: '2026-04-10T10:00:00Z', updated_at: '2026-04-10T10:00:01Z' },
    { extraction_id: 'extr-002', dis_application_id: 'dis-app-001', document_id: 'doc-bank-001', document_type: 'BANK_STATEMENT', tier: 'TIER_1', criticality: 'CRITICAL', extraction_method: 'DOC_AI_FORM_PARSER', processor_id: 'projects/prj-dev-dis-9666/locations/europe-west2/processors/form-parser', processor_version: 'pretrained-v1.0', extraction_confidence: 0.94, raw_extraction: {}, extracted_data: {}, normalised_fields: { account_holder_name: 'KUMARI, RANI', account_number_last4: '8912', sort_code: '12-34-56', bank_name: 'BARCLAYS BANK UK PLC', currency: 'GBP', period_start: '2026-01-01', period_end: '2026-01-31', period_days: 31, opening_balance_gbp: 125000.50, closing_balance_gbp: 138420.75, lowest_balance_gbp: 118500.00, meets_maintenance_threshold: true, salary_credit_detected: true, monthly_salary_amount_gbp: 3500.00 }, fraud_score: 0.12, fraud_status: 'CLEAR', fraud_signals: { metadata_analysis: { score: 0.10, flags: [] }, font_consistency: { score: 0.05, flags: [] }, layout_anomaly: { score: 0.08, flags: [] }, document_quality: { score: 0.03, flags: [] }, cross_doc_consistency: { score: 0.12, flags: [] }, content_plausibility: { score: 0.06, flags: [] } }, source_channel: 'visakey', gcs_raw_path: 'gs://dis-raw-uploads/dis-app-001/doc-bank-001.pdf', gcs_processed_path: 'gs://dis-processed-docs/dis-app-001/doc-bank-001.json', created_at: '2026-04-10T10:00:00Z', updated_at: '2026-04-10T10:00:01Z' },
    { extraction_id: 'extr-003', dis_application_id: 'dis-app-001', document_id: 'doc-emp-001', document_type: 'EMPLOYMENT_LETTER', tier: 'TIER_2', criticality: 'CRITICAL', extraction_method: 'DOC_AI_CUSTOM_EXTRACTOR', processor_id: 'projects/prj-dev-dis-9666/locations/europe-west2/processors/employment-letter-extractor', processor_version: 'custom-v1.0-scrum21', extraction_confidence: 0.91, raw_extraction: {}, extracted_data: {}, normalised_fields: { employer_name: 'ORION TECH SOLUTIONS LTD', job_title: 'IT BUSINESS ANALYST', start_date: '2026-05-01', annual_salary_gbp: 50253.00, hourly_rate_gbp: 25.10, hours_per_week: 38.5, employment_type: 'FULL_TIME', letter_date: '2026-04-01', salary_matches_cos: true, employer_matches_cos: true }, fraud_score: 0.18, fraud_status: 'CLEAR', fraud_signals: { metadata_analysis: { score: 0.10, flags: [] }, font_consistency: { score: 0.15, flags: ['FONT_INCONSISTENCY_DETECTED'] }, layout_anomaly: { score: 0.05, flags: [] }, document_quality: { score: 0.03, flags: [] }, cross_doc_consistency: { score: 0.12, flags: [] }, content_plausibility: { score: 0.08, flags: [] } }, source_channel: 'visakey', gcs_raw_path: 'gs://dis-raw-uploads/dis-app-001/doc-emp-001.pdf', gcs_processed_path: 'gs://dis-processed-docs/dis-app-001/doc-emp-001.json', created_at: '2026-04-10T10:00:00Z', updated_at: '2026-04-10T10:00:02Z' },
    { extraction_id: 'extr-004', dis_application_id: 'dis-app-001', document_id: 'doc-ielts-001', document_type: 'IELTS_CERTIFICATE', tier: 'TIER_2', criticality: 'CRITICAL', extraction_method: 'DOC_AI_CUSTOM_EXTRACTOR', processor_id: 'projects/prj-dev-dis-9666/locations/europe-west2/processors/ielts-extractor', processor_version: 'custom-v1.0-scrum21', extraction_confidence: 0.95, raw_extraction: {}, extracted_data: {}, normalised_fields: { test_type: 'IELTS_ACADEMIC', candidate_name: 'KUMARI, RANI', test_date: '2024-10-12', overall_score: 7.5, listening_score: 8.0, reading_score: 7.5, writing_score: 7.0, speaking_score: 7.5, cefr_level: 'C1', meets_b2_minimum: true, component_scores_valid: true, test_within_2_years: true, trf_number: '24GB012345' }, fraud_score: 0.05, fraud_status: 'CLEAR', fraud_signals: { metadata_analysis: { score: 0.04, flags: [] }, font_consistency: { score: 0.03, flags: [] }, layout_anomaly: { score: 0.02, flags: [] }, document_quality: { score: 0.02, flags: [] }, cross_doc_consistency: { score: 0.08, flags: [] }, content_plausibility: { score: 0.03, flags: [] } }, source_channel: 'visakey', gcs_raw_path: 'gs://dis-raw-uploads/dis-app-001/doc-ielts-001.jpg', gcs_processed_path: 'gs://dis-processed-docs/dis-app-001/doc-ielts-001.json', created_at: '2026-04-10T10:00:00Z', updated_at: '2026-04-10T10:00:02Z' },
    { extraction_id: 'extr-005', dis_application_id: 'dis-app-001', document_id: 'doc-degree-001', document_type: 'DEGREE_CERTIFICATE', tier: 'TIER_2', criticality: 'CRITICAL', extraction_method: 'DOC_AI_CUSTOM_EXTRACTOR', processor_id: 'projects/prj-dev-dis-9666/locations/europe-west2/processors/degree-extractor', processor_version: 'custom-v1.0-scrum21', extraction_confidence: 0.93, raw_extraction: {}, extracted_data: {}, normalised_fields: { institution_name: 'UNIVERSITY OF BIRMINGHAM', candidate_name: 'KUMARI, RANI', qualification_title: 'BACHELOR OF SCIENCE', subject: 'COMPUTER SCIENCE', award_date: '2015-07-20', classification: 'FIRST_CLASS_HONOURS', country_code: 'GBR', is_uk_institution: true, naric_reference: null, rqf_level_equivalent: 6 }, fraud_score: 0.07, fraud_status: 'CLEAR', fraud_signals: { metadata_analysis: { score: 0.06, flags: [] }, font_consistency: { score: 0.04, flags: [] }, layout_anomaly: { score: 0.05, flags: [] }, document_quality: { score: 0.03, flags: [] }, cross_doc_consistency: { score: 0.10, flags: [] }, content_plausibility: { score: 0.04, flags: [] } }, source_channel: 'visakey', gcs_raw_path: 'gs://dis-raw-uploads/dis-app-001/doc-degree-001.jpg', gcs_processed_path: 'gs://dis-processed-docs/dis-app-001/doc-degree-001.json', created_at: '2026-04-10T10:00:00Z', updated_at: '2026-04-10T10:00:02Z' },
  ],

  // === LLM Summary ===
  llm_summary: 'Rani Kumari is a 32-year-old Indian national applying for a Skilled Worker visa sponsored by Orion Tech Solutions Ltd (A-rated, licence MER-2024-7891) for the role of IT Business Analyst (SOC 2135, RQF Level 6). Annual salary of £50,253 comfortably exceeds both the general threshold (£41,700) and the going rate for this occupation (£41,100). All 20 Drools rules passed. The applicant holds a BSc in Computer Science from the University of Birmingham (First Class Honours) which satisfies both the RQF 6+ requirement and provides an English language exemption, further reinforced by an IELTS Academic score of 7.5 (CEFR C1). Financial requirements are met with a lowest balance of £118,500 over the statement period. Two items require officer attention: (1) Reuters World-Check returned a LOW-risk PEP relative match — the applicant\'s father-in-law appears on the India state-level PEP list. This is a soft flag (OPA-S02) for officer assessment, not a sanctions block. (2) The employment letter exhibits a minor font inconsistency (fraud signal score 0.15 on font_consistency) which, while well below the CRITICAL threshold, should be reviewed alongside the original document. All hard OPA policies passed. TB certificate is valid and issued by an approved clinic. No immigration compliance issues.',

  // === Submission metadata ===
  source_application_id: 'VK-2026-RK-4821',
  source_reference: 'VK-2026-RK-4821',
  dis_application_id: 'dis-app-001',
  submitted_at: '2026-04-10T09:59:00Z',
}
